get http://localhost:8080/notes/4


####
post http://localhost:8080/notes
Content-Type: application/json

{
    "title": "last note api",
    "description": "Description",
    "idUser": 4
}


####
put http://localhost:8080/notes/4
Content-Type: application/json

{
    "idUser": 4,
    "title": "New title 2222",
    "description": "Description",
    "isComplete": 1
}


###
delete http://localhost:8080/notes/28
Content-Type: application/json

{
    "idUser": 4
}